# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='cainum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='zannum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='cainum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='zannum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
