# Generated by Django 2.1.2 on 2018-10-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='Title', max_length=40),
            preserve_default=False,
        ),
    ]
