# Generated by Django 2.1.2 on 2018-10-29 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answer', '0002_question_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 13, 12, 58, 534630, tzinfo=utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 13, 12, 58, 518994, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
